namespace NipNip.Data.Entities;

public class PageView
{
    public Guid Id { get; set; }
    public Guid StoreId { get; set; }
    public string Path { get; set; } = "";

    // A long-lived first-party cookie value generated by the storefront itself (not the API),
    // so it's scoped correctly whether the visitor is on a *.nipnip.ge subdomain or a merchant's
    // own custom domain — used only to count unique visitors, never tied to any identity.
    public string VisitorId { get; set; } = "";

    // Normalized hostname (e.g. "instagram.com"), null for direct/no-referrer traffic.
    public string? ReferrerHost { get; set; }
    public DateTimeOffset CreatedAt { get; set; }

    public Store Store { get; set; } = null!;
}
