<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NipNip.Data\NipNip.Data.csproj" />
    <ProjectReference Include="..\NipNip.Shared\NipNip.Shared.csproj" />
    <ProjectReference Include="..\NipNip.Modules.Tracking\NipNip.Modules.Tracking.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic" Version="12.36.0" />
  </ItemGroup>

</Project>
